### ISSUE TITLE
Mondrove structures generating in overworld, is this intended?

### ISSUE THREAD

**Issue by Corvus20** [Cryptic-Cosmos/Cryptic-Cosmos#62]
**Describe the bug**
Mondrove structures are generating in the overworld (possibly in other dimensions too, but I have yet to check)

**To Reproduce**
1.Generate World
2. Search around
3. you'll probably find one within a minute or so

**Expected behavior**
I am not sure if this is intended behavior or not.

**Screenshots**
![2021-05-21_10 50 38](https://user-images.githubusercontent.com/75586106/119157506-40e05f00-ba23-11eb-9745-0dc8e4a8e4b4.png)
![2021-05-21_10 57 05](https://user-images.githubusercontent.com/75586106/119157547-4ccc2100-ba23-11eb-8c13-a04de26f9de0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: version of what?

**Additional context**

**Comment by TheOnlyTails** [comment]
Yes, this is intended.
