### ISSUE TITLE
Axes won't strip logs/ only strips Cryptic Cosmos logs

### ISSUE THREAD

**Issue by GamerGaven** [Cryptic-Cosmos/Cryptic-Cosmos#64]
**Describe the bug**
Right clicking any block with either an Axe or Pickaxe will cause the "stripping" sound effect to play. When an axe right click is used on vanilla or other modded logs they will not strip, while this mods logs will.

**To Reproduce**
1. Load up any world new or old
2. Equip axe or pickaxe to right click any blocks

**Expected behavior**
For logs to be able to strip and for stripping sound to not play when right clicking with axe.

**Screenshots**
None

**Additional context**
Using Forge 36.1.30 and latest version of Cryptic Cosmos

**Comment by callousCelebration** [comment]
An additional component of this bug: Blocks with GUIs cannot be interacted with using an axe or pickaxe.
